<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.1.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.1.0.xsd"
         root="true"
>
    <modelVersion>4.1.0</modelVersion>
    <groupId>com.github.stefanofornari</groupId>
    <artifactId>nb-ste-plugins</artifactId>
    <version>0.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>nb-jwt-editor</module>
        <!--module>modules/nb-javafx-toolkit</module-->
        <module>portal</module>
    </modules>
    
    <properties>
        <nb-javafx-toolkit.version>0.0.2</nb-javafx-toolkit.version>
        <nb-jwt-editor.version>0.0.4</nb-jwt-editor.version>
        <downlaod.url>https://repo.maven.apache.org/maven2/com/github/stefanofornari/nb-jwt-editor</downlaod.url>
    </properties>

    <build>
        <plugins>
            <!-- Enables nbm/nbm-application lifecycles across all submodules globally -->
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <artifactId>nbm-maven-plugin</artifactId>
                <extensions>true</extensions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.4.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.netbeans.utilities</groupId>
                    <artifactId>nbm-maven-plugin</artifactId>
                    <version>14.4</version>
                    <extensions>true</extensions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.1.2</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>